Module: Lich Pet Summon fix
AnneTrue/nexus-clash-interface-tweaks pull request #23
Opened 2022-02-09 00:40 UTC by Argavyon

Makes the overly wide petlist for liches with summon zombie+skeleton+FM+necro more eye-friendly.

Goes from this
![Screenshot_3](https://user-images.githubusercontent.com/75849479/153099857-9e86fdeb-fee2-4467-af87-6da6062259fb.jpg)
To this
![Screenshot_4](https://user-images.githubusercontent.com/75849479/153099870-ea38ab3c-5334-4553-8b35-08159be3405c.jpg)

2022-02-09 01:33 UTC, AnneTrue requested changes
Two overall questions:
- Are the devs fixing this directly? This is very much a problem they should fix.
- Is this problem actually specific to liches because they have the dual titans, or will other classes benefit from a more generic approach?

Besides that, needs the usual check-off of pre-merge items such as README documentation and version bumps.

2022-02-09 01:33 UTC, AnneTrue commented on nexus-tweaks.user.js
> +    const FM = petSummons.querySelector('input[value="Fossil Monstrosity"]');
Style-wise it's consistent as "fossilMonstrosity", rather than all-caps.

2022-02-09 01:33 UTC, AnneTrue commented on nexus-tweaks.user.js
> +      FM.nextSibling.value = 'Fossil Monstrosity (3 Skeletons) '
What's the purpose of this? Are you cutting off the MP cost?

2022-02-09 01:33 UTC, AnneTrue commented on nexus-tweaks.user.js
> +      petSummons.children[2].insertBefore(FM.parentNode.parentNode, petSummons.children[2].firstChild);
When you're manipulating DOM elements with relative positions like this, it helps a lot to document what you expect those elements to be.

2022-02-15 11:38 UTC, Argavyon commented
Version bumping isn't trivial from my side, as I can't tell what will be merged first. (In particular, whether this will be merged before the badge classifier).
This would be an even larger issue if someone else was sending PRs.

2022-06-22 01:50 UTC, closed without merging